# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 77d4957ac0d0e8099d2bc93d953b739ea8aece6a9263973a5e597b8be4172ee1ffd2fd8db1d49064a326a35872d27d87be9affd42a5be12a5d86049b257fe04c

test:
  secret_key_base: c936b82c11e2781a070cb51b1414df4e50f8eb86362bc00c444e3d2f0b2692f941b696b7194c4b0531a11a8eddfa46754508583e3cbcca98b11ba0b80b146ab6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
